### ISSUE TITLE
无法下载视频

### ISSUE THREAD

**Issue by KatyushaScarlet** [morris13579/NTUT_ISchool_Downloader#2]
能够获取视频列表，但无法下载视频
i学园plus换了新的播放器，不再是之前的flash播放器，可以直接从页面get请求中获取视频下载链接

**Comment by morris13579** [comment]
目前已經修正此問題了

**Comment by KatyushaScarlet** [comment]
感谢！

**Comment by KatyushaScarlet** [comment]
依旧下载失败，并显示文件大小0kb

课程号：
1091_演算法分析與設計_280169

程式输出：
https://istream.ntut.edu.tw/videoplayer/player.php?vid=YXFKcmVyS3QrUzBVUHVrUGI0Z2pUUDZManY3K1B6RkhDakNscUpYQkl0TVZNa3dxYUVRYy91amdEVitIek1BeGpBZFVRMm8wdU11YWZqTTI1NDJ0TXJhTmNDbDcrQyszdkNkOEhIbm10Y1lwU2tGN1cyOGZUaFJtcnRKQ2pYNms6OjKQf%2BSru5KQW%2FIQgvMAzoA%3D

[錄] 09231712
src_presenter
按Enter下載 or 輸入(Y/N):y
https://istream.ntut.edu.tw/videoplayer/lectureStream.php?channel=presenter&vid=YXFKcmVyS3QrUzBVUHVrUGI0Z2pUUDZManY3K1B6RkhDakNscUpYQkl0TVZNa3dxYUVRYy91amdEVitIek1BeGpBZFVRMm8wdU11YWZqTTI1NDJ0TXJhTmNDbDcrQyszdkNkOEhIbm10Y1lwU2tGN1cyOGZUaFJtcnRKQ2pYNms6OjKQf+Sru5KQW/IQgvMAzoA=

[錄] 09231712_src_presenter.mp4                                                  下載完成 0.00 KB / 0.00 KB
src_presentation
按Enter下載 or 輸入(Y/N):y
https://istream.ntut.edu.tw/videoplayer/lectureStream.php?channel=presenter2&vid=YXFKcmVyS3QrUzBVUHVrUGI0Z2pUUDZManY3K1B6RkhDakNscUpYQkl0TVZNa3dxYUVRYy91amdEVitIek1BeGpBZFVRMm8wdU11YWZqTTI1NDJ0TXJhTmNDbDcrQyszdkNkOEhIbm10Y1lwU2tGN1cyOGZUaFJtcnRKQ2pYNms6OjKQf+Sru5KQW/IQgvMAzoA=

[錄] 09231712_src_presentation.mp4                                               下載完成 0.00 KB / 0.00 KB
按任意建結束

**Comment by morris13579** [comment]
我這裡是可以下載正常的，可以去I Plus看看能不能看錄影，如果去網頁就不能觀看，那下載出錯就是正常的。

**Comment by KatyushaScarlet** [comment]
又尝试了几个录影，发现可以正常下载了，可能是网路有点波动
